server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: config-server
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/JetBrains/IdeaProjects/git/etb-spring-cloud-config
  #cloud:
    #config:
      #server:
        #git:
          #uri: https://github.com/solargen/aigou-config.git
          #username: xxc9830
          #password: xxc.9830
